In [1]:
print('hello world')

hello world

In [2]:
import pandas as pd

In [6]:
pd.read_csv('Trump vs. Biden - Sheet1.csv')

,2016 election,Unnamed: 1,2020 Election,Unnamed: 3
0,Hillary Clinton,Donal Trump,Joe Biden,Donald Trump
1,227,304,306,232
2,48%,46%,51%,47%
3,"65,853,514","62,984,828","79,271,864","73,464,544"
4,NaN,NaN,NaN,NaN
5,Demogrpahics,NaN,NaN,NaN
6,NaN,Trump,Biden,NaN
7,Male48% of voters,53%,45%,NaN
8,Female52%,42,57,NaN
9,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN
11,NaN,Trump,Biden,NaN
12,White67% of voters,58,41,NaN
13,Black13%,12,87,NaN
14,Hispanic/Latino13%,32,65,NaN
15,Asian4%,34,61,NaN
16,Other4%,41,55,NaN
17,NaN,NaN,NaN,NaN
18,18-2917% of voters,36,60,Age Range
19,30-44 23%,46,52,NaN
20,45-64 38%,50,49,NaN
21,65 or over 22%,52,47,NaN
22,NaN,NaN,NaN,NaN
23,College graduate41% of voters,43,55,Education Level
24,No college degree59%,50,48,NaN
25,NaN,NaN,NaN,NaN
26,Yes 56% of voters,53,46,Married?
27,No 44%,40,58,NaN
28,NaN,NaN,NaN,NaN
29,Yes 7% of voters,27,64,"gay, lesbian, bisexual or transgender?"
30,No 93%,48,51,NaN
31,NaN,NaN,NaN,NaN
32,"Under $50,00035% of voters",44,55,Total income 2019
33,"$50,000-$99,99939%",42,57,NaN
34,"$100,000 or more26%",54,42,NaN
35,NaN,NaN,NaN,NaN
36,Better today 41% of voters,72,26,Financial situation
37,Worse today 20%,20,77,NaN
38,About the same 39%,34,65,NaN

In [7]:
df.head(10)

      2016 election     Unnamed: 1 2020 Election    Unnamed: 3
0   Hillary Clinton   Donal Trump      Joe Biden  Donald Trump
1                227           304           306           232
2                48%           46%           51%           47%
3         65,853,514    62,984,828    79,271,864    73,464,544
4                NaN           NaN           NaN           NaN
5       Demogrpahics           NaN           NaN           NaN
6                NaN         Trump         Biden           NaN
7  Male48% of voters           53%           45%           NaN
8          Female52%            42            57           NaN
9                NaN           NaN           NaN           NaN

In [12]:
df.tail(10)

,2016 election,Unnamed: 1,2020 Election,Unnamed: 3
29,Yes 7% of voters,27,64,"gay, lesbian, bisexual or transgender?"
30,No 93%,48,51,NaN
31,NaN,NaN,NaN,NaN
32,"Under $50,00035% of voters",44,55,Total income 2019
33,"$50,000-$99,99939%",42,57,NaN
34,"$100,000 or more26%",54,42,NaN
35,NaN,NaN,NaN,NaN
36,Better today 41% of voters,72,26,Financial situation
37,Worse today 20%,20,77,NaN
38,About the same 39%,34,65,NaN

In [15]:
df.sample(10)

        2016 election   Unnamed: 1 2020 Election  Unnamed: 3
8            Female52%          42            57         NaN
21      65 or over 22%          52            47         NaN
5         Demogrpahics         NaN           NaN         NaN
33  $50,000-$99,99939%          42            57         NaN
14  Hispanic/Latino13%          32            65         NaN
25                 NaN         NaN           NaN         NaN
11                 NaN      Trump          Biden         NaN
37     Worse today 20%          20            77         NaN
20           45-64 38%          50            49         NaN
3           65,853,514  62,984,828    79,271,864  73,464,544

In [18]:
df.shape

(39, 4)

TypeError: 'tuple' object is not callable